- name: Copy Filebeat YUm Repo
  ansible.builtin.template:
    src: filebeat.repo
    dest: /etc/yum.repos.d/filebeat.repo

- name: Install Filebeat
  ansible.builtin.yum:
    name: filebeat
    state: installed

- name: Start filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: yes



