- name: Copy Prometheus Configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml
  notify: Restart prometheus

- name: Wait for Prometheus to start
  ansible.builtin.wait_for:
    port: 9090
    delay: 10
    timeout: 30





